name: carmapy
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4>=4.9.0
  - gensim=3.8.0
  - ipywidgets>=7.5
  - jupyterlab=1.2.6
  - lxml=4.5.0
  - nltk=3.4.5
  - nodejs=10.13.0
  - pandas=1.0.3
  - pandas-datareader>=0.8.1
  - pip>=19.3.1
  - plotly=4.7.1
  - pyarrow=0.13.0
  - python=3.7
  - requests=2.23.0
  - scikit-learn=0.22.1
  - spacy=2.2.4
  - statsmodels>=0.10
  - tensorflow=2.0
  - textblob=0.15.3
  - pip:
    - linearmodels==4.15.4
    - nytimesarticle==0.1.0
